import 'dart:convert';
import 'package:ccm/models/response.dart';

import '../services/firebase.dart' as firebase;
// To parse this JSON data, do
//
//     final country = countryFromJson(jsonString);

Country countryFromJson(String str) => Country.fromJson(json.decode(str));

String countryToJson(Country data) => json.encode(data.toJson());

class Country {
  Country({
    required this.name,
    this.currencyCode,
    required this.code,
  });

  @override
  bool operator ==(other) {
    if (other is Country) {
      return this.code == other.code;
    } else
      return false;
  }

  String name;
  String? currencyCode;
  String code;

  @override
  String toString() {
    return name;
  }

  factory Country.fromJson(Map<String, dynamic> json) => Country(
        name: json["name"],
        currencyCode: json["currencyCode"],
        code: json["code"],
      );

  Map<String, dynamic> toJson() => {
        "name": name,
        "currencyCode": currencyCode,
        "code": code,
      };

  add() {
    return firebase.countries
        .doc(code)
        .set(toJson())
        .then((value) => Result.success("Country Added successfully"))
        .onError((error, stackTrace) => Result.error(error));
  }

  static const _countryList = [
    {"name": "New Zealand", "code": "NZ", "currencyCode": "NZD"},
    {"name": "Cook Islands", "code": "CK", "currencyCode": "NZD"},
    {"name": "Niue", "code": "NU", "currencyCode": "NZD"},
    {"name": "Pitcairn", "code": "PN", "currencyCode": "NZD"},
    {"name": "Tokelau", "code": "TK", "currencyCode": "NZD"},
    {"name": "Australian", "code": "AU", "currencyCode": "AUD"},
    {"name": "Christmas Island", "code": "CX", "currencyCode": "AUD"},
    {"name": "Cocos (Keeling) Islands", "code": "CC", "currencyCode": "AUD"},
    {"name": "Heard and Mc Donald Islands", "code": "HM", "currencyCode": "AUD"},
    {"name": "Kiribati", "code": "KI", "currencyCode": "AUD"},
    {"name": "Nauru", "code": "NR", "currencyCode": "AUD"},
    {"name": "Norfolk Island", "code": "NF", "currencyCode": "AUD"},
    {"name": "Tuvalu", "code": "TV", "currencyCode": "AUD"},
    {"name": "American Samoa", "code": "AS", "currencyCode": "EUR"},
    {"name": "Andorra", "code": "AD", "currencyCode": "EUR"},
    {"name": "Austria", "code": "AT", "currencyCode": "EUR"},
    {"name": "Belgium", "code": "BE", "currencyCode": "EUR"},
    {"name": "Finland", "code": "FI", "currencyCode": "EUR"},
    {"name": "France", "code": "FR", "currencyCode": "EUR"},
    {"name": "French Guiana", "code": "GF", "currencyCode": "EUR"},
    {"name": "French Southern Territories", "code": "TF", "currencyCode": "EUR"},
    {"name": "Germany", "code": "DE", "currencyCode": "EUR"},
    {"name": "Greece", "code": "GR", "currencyCode": "EUR"},
    {"name": "Guadeloupe", "code": "GP", "currencyCode": "EUR"},
    {"name": "Ireland", "code": "IE", "currencyCode": "EUR"},
    {"name": "Italy", "code": "IT", "currencyCode": "EUR"},
    {"name": "Luxembourg", "code": "LU", "currencyCode": "EUR"},
    {"name": "Martinique", "code": "MQ", "currencyCode": "EUR"},
    {"name": "Mayotte", "code": "YT", "currencyCode": "EUR"},
    {"name": "Monaco", "code": "MC", "currencyCode": "EUR"},
    {"name": "Netherlands", "code": "NL", "currencyCode": "EUR"},
    {"name": "Portugal", "code": "PT", "currencyCode": "EUR"},
    {"name": "Reunion", "code": "RE", "currencyCode": "EUR"},
    {"name": "Samoa", "code": "WS", "currencyCode": "EUR"},
    {"name": "San Marino", "code": "SM", "currencyCode": "EUR"},
    {"name": "Slovenia", "code": "SI", "currencyCode": "EUR"},
    {"name": "Spain", "code": "ES", "currencyCode": "EUR"},
    {"name": "Vatican City State (Holy See)", "code": "VA", "currencyCode": "EUR"},
    {"name": "South Georgia and the South Sandwich Islands", "code": "GS", "currencyCode": "GBP"},
    {"name": "United Kingdom", "code": "GB", "currencyCode": "GBP"},
    {"name": "Jersey", "code": "JE", "currencyCode": "GBP"},
    {"name": "British Indian Ocean Territory", "code": "IO", "currencyCode": "USD"},
    {"name": "Guam", "code": "GU", "currencyCode": "USD"},
    {"name": "Marshall Islands", "code": "MH", "currencyCode": "USD"},
    {"name": "Micronesia Federated States of", "code": "FM", "currencyCode": "USD"},
    {"name": "Northern Mariana Islands", "code": "MP", "currencyCode": "USD"},
    {"name": "Palau", "code": "PW", "currencyCode": "USD"},
    {"name": "Puerto Rico", "code": "PR", "currencyCode": "USD"},
    {"name": "Turks and Caicos Islands", "code": "TC", "currencyCode": "USD"},
    {"name": "United States", "code": "US", "currencyCode": "USD"},
    {"name": "United States Minor Outlying Islands", "code": "UM", "currencyCode": "USD"},
    {"name": "Virgin Islands (British)", "code": "VG", "currencyCode": "USD"},
    {"name": "Virgin Islands (US)", "code": "VI", "currencyCode": "USD"},
    {"name": "Hong Kong", "code": "HK", "currencyCode": "HKD"},
    {"name": "Canada", "code": "CA", "currencyCode": "CAD"},
    {"name": "Japan", "code": "JP", "currencyCode": "JPY"},
    {"name": "Afghanistan", "code": "AF", "currencyCode": "AFN"},
    {"name": "Albania", "code": "AL", "currencyCode": "ALL"},
    {"name": "Algeria", "code": "DZ", "currencyCode": "DZD"},
    {"name": "Anguilla", "code": "AI", "currencyCode": "XCD"},
    {"name": "Antigua and Barbuda", "code": "AG", "currencyCode": "XCD"},
    {"name": "Dominica", "code": "DM", "currencyCode": "XCD"},
    {"name": "Grenada", "code": "GD", "currencyCode": "XCD"},
    {"name": "Montserrat", "code": "MS", "currencyCode": "XCD"},
    {"name": "Saint Kitts", "code": "KN", "currencyCode": "XCD"},
    {"name": "Saint Lucia", "code": "LC", "currencyCode": "XCD"},
    {"name": "Saint Vincent Grenadines", "code": "VC", "currencyCode": "XCD"},
    {"name": "Argentina", "code": "AR", "currencyCode": "ARS"},
    {"name": "Armenia", "code": "AM", "currencyCode": "AMD"},
    {"name": "Aruba", "code": "AW", "currencyCode": "ANG"},
    {"name": "Netherlands Antilles", "code": "AN", "currencyCode": "ANG"},
    {"name": "Azerbaijan", "code": "AZ", "currencyCode": "AZN"},
    {"name": "Bahamas", "code": "BS", "currencyCode": "BSD"},
    {"name": "Bahrain", "code": "BH", "currencyCode": "BHD"},
    {"name": "Bangladesh", "code": "BD", "currencyCode": "BDT"},
    {"name": "Barbados", "code": "BB", "currencyCode": "BBD"},
    {"name": "Belarus", "code": "BY", "currencyCode": "BYR"},
    {"name": "Belize", "code": "BZ", "currencyCode": "BZD"},
    {"name": "Benin", "code": "BJ", "currencyCode": "XOF"},
    {"name": "Burkina Faso", "code": "BF", "currencyCode": "XOF"},
    {"name": "Guinea-Bissau", "code": "GW", "currencyCode": "XOF"},
    {"name": "Ivory Coast", "code": "CI", "currencyCode": "XOF"},
    {"name": "Mali", "code": "ML", "currencyCode": "XOF"},
    {"name": "Niger", "code": "NE", "currencyCode": "XOF"},
    {"name": "Senegal", "code": "SN", "currencyCode": "XOF"},
    {"name": "Togo", "code": "TG", "currencyCode": "XOF"},
    {"name": "Bermuda", "code": "BM", "currencyCode": "BMD"},
    {"name": "Bhutan", "code": "BT", "currencyCode": "INR"},
    {"name": "India", "code": "IN", "currencyCode": "INR"},
    {"name": "Bolivia", "code": "BO", "currencyCode": "BOB"},
    {"name": "Botswana", "code": "BW", "currencyCode": "BWP"},
    {"name": "Bouvet Island", "code": "BV", "currencyCode": "NOK"},
    {"name": "Norway", "code": "NO", "currencyCode": "NOK"},
    {"name": "Svalbard and Jan Mayen Islands", "code": "SJ", "currencyCode": "NOK"},
    {"name": "Brazil", "code": "BR", "currencyCode": "BRL"},
    {"name": "Brunei Darussalam", "code": "BN", "currencyCode": "BND"},
    {"name": "Bulgaria", "code": "BG", "currencyCode": "BGN"},
    {"name": "Burundi", "code": "BI", "currencyCode": "BIF"},
    {"name": "Cambodia", "code": "KH", "currencyCode": "KHR"},
    {"name": "Cameroon", "code": "CM", "currencyCode": "XAF"},
    {"name": "Central African Republic", "code": "CF", "currencyCode": "XAF"},
    {"name": "Chad", "code": "TD", "currencyCode": "XAF"},
    {"name": "Congo Republic of the Democratic", "code": "CG", "currencyCode": "XAF"},
    {"name": "Equatorial Guinea", "code": "GQ", "currencyCode": "XAF"},
    {"name": "Gabon", "code": "GA", "currencyCode": "XAF"},
    {"name": "Cape Verde", "code": "CV", "currencyCode": "CVE"},
    {"name": "Cayman Islands", "code": "KY", "currencyCode": "KYD"},
    {"name": "Chile", "code": "CL", "currencyCode": "CLP"},
    {"name": "China", "code": "CN", "currencyCode": "CNY"},
    {"name": "Colombia", "code": "CO", "currencyCode": "COP"},
    {"name": "Comoros", "code": "KM", "currencyCode": "KMF"},
    {"name": "Congo-Brazzaville", "code": "CD", "currencyCode": "CDF"},
    {"name": "Costa Rica", "code": "CR", "currencyCode": "CRC"},
    {"name": "Croatia (Hrvatska)", "code": "HR", "currencyCode": "HRK"},
    {"name": "Cuba", "code": "CU", "currencyCode": "CUP"},
    {"name": "Cyprus", "code": "CY", "currencyCode": "CYP"},
    {"name": "Czech Republic", "code": "CZ", "currencyCode": "CZK"},
    {"name": "Denmark", "code": "DK", "currencyCode": "DKK"},
    {"name": "Faroe Islands", "code": "FO", "currencyCode": "DKK"},
    {"name": "Greenland", "code": "GL", "currencyCode": "DKK"},
    {"name": "Djibouti", "code": "DJ", "currencyCode": "DJF"},
    {"name": "Dominican Republic", "code": "DO", "currencyCode": "DOP"},
    {"name": "East Timor", "code": "TP", "currencyCode": "IDR"},
    {"name": "Indonesia", "code": "ID", "currencyCode": "IDR"},
    {"name": "Ecuador", "code": "EC", "currencyCode": "ECS"},
    {"name": "Egypt", "code": "EG", "currencyCode": "EGP"},
    {"name": "El Salvador", "code": "SV", "currencyCode": "SVC"},
    {"name": "Eritrea", "code": "ER", "currencyCode": "ETB"},
    {"name": "Ethiopia", "code": "ET", "currencyCode": "ETB"},
    {"name": "Estonia", "code": "EE", "currencyCode": "EEK"},
    {"name": "Falkland Islands (Malvinas)", "code": "FK", "currencyCode": "FKP"},
    {"name": "Fiji", "code": "FJ", "currencyCode": "FJD"},
    {"name": "French Polynesia", "code": "PF", "currencyCode": "XPF"},
    {"name": "New Caledonia", "code": "NC", "currencyCode": "XPF"},
    {"name": "Wallis and Futuna Islands", "code": "WF", "currencyCode": "XPF"},
    {"name": "Gambia", "code": "GM", "currencyCode": "GMD"},
    {"name": "Georgia", "code": "GE", "currencyCode": "GEL"},
    {"name": "Gibraltar", "code": "GI", "currencyCode": "GIP"},
    {"name": "Guatemala", "code": "GT", "currencyCode": "GTQ"},
    {"name": "Guinea", "code": "GN", "currencyCode": "GNF"},
    {"name": "Guyana", "code": "GY", "currencyCode": "GYD"},
    {"name": "Haiti", "code": "HT", "currencyCode": "HTG"},
    {"name": "Honduras", "code": "HN", "currencyCode": "HNL"},
    {"name": "Hungary", "code": "HU", "currencyCode": "HUF"},
    {"name": "Iceland", "code": "IS", "currencyCode": "ISK"},
    {"name": "Iran (Islamic Republic of)", "code": "IR", "currencyCode": "IRR"},
    {"name": "Iraq", "code": "IQ", "currencyCode": "IQD"},
    {"name": "Israel", "code": "IL", "currencyCode": "ILS"},
    {"name": "Jamaica", "code": "JM", "currencyCode": "JMD"},
    {"name": "Jordan", "code": "JO", "currencyCode": "JOD"},
    {"name": "Kazakhstan", "code": "KZ", "currencyCode": "KZT"},
    {"name": "Kenya", "code": "KE", "currencyCode": "KES"},
    {"name": "Korea North", "code": "KP", "currencyCode": "KPW"},
    {"name": "Korea South", "code": "KR", "currencyCode": "KRW"},
    {"name": "Kuwait", "code": "KW", "currencyCode": "KWD"},
    {"name": "Kyrgyzstan", "code": "KG", "currencyCode": "KGS"},
    {"name": "Lao PeopleÕs Democratic Republic", "code": "LA", "currencyCode": "LAK"},
    {"name": "Latvia", "code": "LV", "currencyCode": "LVL"},
    {"name": "Lebanon", "code": "LB", "currencyCode": "LBP"},
    {"name": "Lesotho", "code": "LS", "currencyCode": "LSL"},
    {"name": "Liberia", "code": "LR", "currencyCode": "LRD"},
    {"name": "Libyan Arab Jamahiriya", "code": "LY", "currencyCode": "LYD"},
    {"name": "Liechtenstein", "code": "LI", "currencyCode": "CHF"},
    {"name": "Switzerland", "code": "CH", "currencyCode": "CHF"},
    {"name": "Lithuania", "code": "LT", "currencyCode": "LTL"},
    {"name": "Macau", "code": "MO", "currencyCode": "MOP"},
    {"name": "Macedonia", "code": "MK", "currencyCode": "MKD"},
    {"name": "Madagascar", "code": "MG", "currencyCode": "MGA"},
    {"name": "Malawi", "code": "MW", "currencyCode": "MWK"},
    {"name": "Malaysia", "code": "MY", "currencyCode": "MYR"},
    {"name": "Maldives", "code": "MV", "currencyCode": "MVR"},
    {"name": "Malta", "code": "MT", "currencyCode": "MTL"},
    {"name": "Mauritania", "code": "MR", "currencyCode": "MRO"},
    {"name": "Mauritius", "code": "MU", "currencyCode": "MUR"},
    {"name": "Mexico", "code": "MX", "currencyCode": "MXN"},
    {"name": "Moldova Republic of", "code": "MD", "currencyCode": "MDL"},
    {"name": "Mongolia", "code": "MN", "currencyCode": "MNT"},
    {"name": "Morocco", "code": "MA", "currencyCode": "MAD"},
    {"name": "Western Sahara", "code": "EH", "currencyCode": "MAD"},
    {"name": "Mozambique", "code": "MZ", "currencyCode": "MZN"},
    {"name": "Myanmar", "code": "MM", "currencyCode": "MMK"},
    {"name": "Namibia", "code": "NA", "currencyCode": "NAD"},
    {"name": "Nepal", "code": "NP", "currencyCode": "NPR"},
    {"name": "Nicaragua", "code": "NI", "currencyCode": "NIO"},
    {"name": "Nigeria", "code": "NG", "currencyCode": "NGN"},
    {"name": "Oman", "code": "OM", "currencyCode": "OMR"},
    {"name": "Pakistan", "code": "PK", "currencyCode": "PKR"},
    {"name": "Panama", "code": "PA", "currencyCode": "PAB"},
    {"name": "Papua New Guinea", "code": "PG", "currencyCode": "PGK"},
    {"name": "Paraguay", "code": "PY", "currencyCode": "PYG"},
    {"name": "Peru", "code": "PE", "currencyCode": "PEN"},
    {"name": "Philippines", "code": "PH", "currencyCode": "PHP"},
    {"name": "Poland", "code": "PL", "currencyCode": "PLN"},
    {"name": "Qatar", "code": "QA", "currencyCode": "QAR"},
    {"name": "Romania", "code": "RO", "currencyCode": "RON"},
    {"name": "Russian Federation", "code": "RU", "currencyCode": "RUB"},
    {"name": "Rwanda", "code": "RW", "currencyCode": "RWF"},
    {"name": "Sao Tome and Principe", "code": "ST", "currencyCode": "STD"},
    {"name": "Saudi Arabia", "code": "SA", "currencyCode": "SAR"},
    {"name": "Seychelles", "code": "SC", "currencyCode": "SCR"},
    {"name": "Sierra Leone", "code": "SL", "currencyCode": "SLL"},
    {"name": "Singapore", "code": "SG", "currencyCode": "SGD"},
    {"name": "Slovakia (Slovak Republic)", "code": "SK", "currencyCode": "SKK"},
    {"name": "Solomon Islands", "code": "SB", "currencyCode": "SBD"},
    {"name": "Somalia", "code": "SO", "currencyCode": "SOS"},
    {"name": "South Africa", "code": "ZA", "currencyCode": "ZAR"},
    {"name": "Sri Lanka", "code": "LK", "currencyCode": "LKR"},
    {"name": "Sudan", "code": "SD", "currencyCode": "SDG"},
    {"name": "Suriname", "code": "SR", "currencyCode": "SRD"},
    {"name": "Swaziland", "code": "SZ", "currencyCode": "SZL"},
    {"name": "Sweden", "code": "SE", "currencyCode": "SEK"},
    {"name": "Syrian Arab Republic", "code": "SY", "currencyCode": "SYP"},
    {"name": "Taiwan", "code": "TW", "currencyCode": "TWD"},
    {"name": "Tajikistan", "code": "TJ", "currencyCode": "TJS"},
    {"name": "Tanzania", "code": "TZ", "currencyCode": "TZS"},
    {"name": "Thailand", "code": "TH", "currencyCode": "THB"},
    {"name": "Tonga", "code": "TO", "currencyCode": "TOP"},
    {"name": "Trinidad and Tobago", "code": "TT", "currencyCode": "TTD"},
    {"name": "Tunisia", "code": "TN", "currencyCode": "TND"},
    {"name": "Turkey", "code": "TR", "currencyCode": "TRY"},
    {"name": "Turkmenistan", "code": "TM", "currencyCode": "TMT"},
    {"name": "Uganda", "code": "UG", "currencyCode": "UGX"},
    {"name": "Ukraine", "code": "UA", "currencyCode": "UAH"},
    {"name": "United Arab Emirates", "code": "AE", "currencyCode": "AED"},
    {"name": "Uruguay", "code": "UY", "currencyCode": "UYU"},
    {"name": "Uzbekistan", "code": "UZ", "currencyCode": "UZS"},
    {"name": "Vanuatu", "code": "VU", "currencyCode": "VUV"},
    {"name": "Venezuela", "code": "VE", "currencyCode": "VEF"},
    {"name": "Vietnam", "code": "VN", "currencyCode": "VND"},
    {"name": "Yemen", "code": "YE", "currencyCode": "YER"},
    {"name": "Zambia", "code": "ZM", "currencyCode": "ZMK"},
    {"name": "Zimbabwe", "code": "ZW", "currencyCode": "ZWD"},
    {"name": "Aland Islands", "code": "AX", "currencyCode": "EUR"},
    {"name": "Angola", "code": "AO", "currencyCode": "AOA"},
    {"name": "Antarctica", "code": "AQ", "currencyCode": "AQD"},
    {"name": "Bosnia and Herzegovina", "code": "BA", "currencyCode": "BAM"},
    {"name": "Congo (Kinshasa)", "code": "CD", "currencyCode": "CDF"},
    {"name": "Ghana", "code": "GH", "currencyCode": "GHS"},
    {"name": "Guernsey", "code": "GG", "currencyCode": "GGP"},
    {"name": "Isle of Man", "code": "IM", "currencyCode": "GBP"},
    {"name": "Laos", "code": "LA", "currencyCode": "LAK"},
    {"name": "Macao S.A.R.", "code": "MO", "currencyCode": "MOP"},
    {"name": "Montenegro", "code": "ME", "currencyCode": "EUR"},
    {"name": "Palestinian Territory", "code": "PS", "currencyCode": "JOD"},
    {"name": "Saint Barthelemy", "code": "BL", "currencyCode": "EUR"},
    {"name": "Saint Helena", "code": "SH", "currencyCode": "GBP"},
    {"name": "Saint Martin (French part)", "code": "MF", "currencyCode": "ANG"},
    {"name": "Saint Pierre and Miquelon", "code": "PM", "currencyCode": "EUR"},
    {"name": "Serbia", "code": "RS", "currencyCode": "RSD"},
    {"name": "US Armed Forces", "code": "USAF", "currencyCode": "USD"}
  ];

  static List<Country> get countries => _countryList.map((e) => Country.fromJson(e)).toList();

  @override
  // ignore: todo
  // TODO: implement hashCode
  int get hashCode => super.hashCode;
}
